# Generated by Django 5.1.4 on 2024-12-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_reader_alter_book_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookrelation',
            name='rating',
            field=models.PositiveBigIntegerField(choices=[(1, 'Poop'), (2, 'Not bad'), (3, 'Normal'), (4, 'Good'), (5, 'Great')]),
        ),
    ]
