# Generated by Django 5.1.4 on 2024-12-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_userbookrelation_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookrelation',
            name='rating',
            field=models.PositiveBigIntegerField(choices=[(1, 'Poop'), (2, 'Not bad'), (3, 'Normal'), (4, 'Good'), (5, 'Great')], null=True),
        ),
    ]
