# Generated by Django 5.1.4 on 2024-12-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_book_max_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='max_rating',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=3, null=True),
        ),
    ]
